### ISSUE TITLE
[EXPIRED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [viralpoetry/VPcrypt#1]
Dear Peter,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by viralpoetry** [comment]
Hi,
are you doing some social research asking dozens of repositories to provide Windows binaries?

**Comment by sergeevabc** [comment]
@viralpoetry, trying to get a little good out of nerds’ developments for mere users. Niche of crypto tools, i.e. tools which turn sensitive data into garbage and back with correct key, is highly underdeveloped,

**Comment by viralpoetry** [comment]
I will provide the binary, but cannot commit to the exact date, as this code is not finished yet. I want to add few more features (ascii armor, pbkdf iteration set by commandline)

**Comment by sergeevabc** [comment]
Speaking of features, I’m surprised how you mix up modern and conservative solutions, i.e. XSalsa20 by Daniel Bernstein works well with his other creation for integrity check, which is Poly1305, but you chosen HMACSHA2. Why?

**Comment by viralpoetry** [comment]
The true is that I have chosen which I known at that time. I was playing with the Sodium library (NaCl) and was familiar with the traditional hash functions as SHA family.
Another problem is, as NaCl is primarily a network crypto library with fixed blocks, I had to chain MAC computations, which is slow quite slow for large files as a side effect.
